Feat/journey management
NoSleepFullBuild/Uniride-frontend pull request #17
Opened 2024-02-04 13:50 UTC by Ronfflex

2024-02-05 13:26 UTC, MTthoas commented on App.tsx
>  export type RootStackParamList = {
Tout les types doivent être externalisés au fichier, généralement un dossier types existes

2024-02-05 13:28 UTC, MTthoas commented on screens/publish/DetailsPublishScreen.tsx
> +type DetailsPublishScreenNavigationProp = StackNavigationProp<
Types must be extern

2024-02-05 13:29 UTC, MTthoas requested changes
Only types feat

2024-02-05 13:38 UTC, Ronfflex commented on App.tsx
>  export type RootStackParamList = {
Oui oui allez ratio

2024-02-05 13:38 UTC, Ronfflex commented on screens/publish/DetailsPublishScreen.tsx
> +type DetailsPublishScreenNavigationProp = StackNavigationProp<
Oui oui allez double ratio

2024-02-05 13:39 UTC, Ronfflex commented
@MTthoas Valide ma PR !

2024-02-06 15:34 UTC, MTthoas commented on App.tsx
>  export type RootStackParamList = {
Fix moi ca gros dog

2024-02-06 15:34 UTC, MTthoas commented on components/inputBar/InputBar.tsx
> +type InputBarProps = {
Encore un type

2024-02-06 15:35 UTC, MTthoas commented on context/AppContext.tsx
> +interface AppContextInterface {
Degage moi ca bordel

2024-02-06 15:35 UTC, MTthoas commented on context/AppContext.tsx
> +export const AppContext = createContext<AppContextInterface>({
Tu fais espret

2024-02-06 15:35 UTC, MTthoas commented on screens/publish/ArrivalPublishScreen.tsx
> +type ArrivalPublishScreenNavigationProp = StackNavigationProp<
Types

2024-02-06 15:35 UTC, MTthoas commented on screens/publish/ArrivalPublishScreen.tsx
> +type Props = {
Type

2024-02-06 15:35 UTC, MTthoas commented on screens/publish/DeparturePublishScreen.tsx
> +type DeparturePublishScreenNavigationProp = StackNavigationProp<
Type

2024-02-06 15:35 UTC, MTthoas commented on screens/publish/DeparturePublishScreen.tsx
> +type Props = {
Type

2024-02-06 15:35 UTC, Ronfflex commented
@MTthoas T ban

2024-02-06 15:35 UTC, MTthoas commented on screens/publish/DeparturePublishScreen.tsx
> +const DeparturePublishScreen = ({ navigation }: Props) => {
Const

2024-02-06 15:36 UTC, MTthoas commented on screens/publish/DetailsPublishScreen.tsx
> +type Props = {
DEGAGE MOI CA DU FICHIER

2024-02-06 15:36 UTC, MTthoas commented on screens/publish/DetailsPublishScreen.tsx
> +type DetailsPublishScreenNavigationProp = StackNavigationProp<
NON

2024-02-06 15:36 UTC, MTthoas requested changes
1 TYPES ou une interface dans un componentfile =  pour les prochaines fois = 1 fuzeTea

2024-02-06 20:02 UTC, MTthoas approved these changes

2024-02-06 20:02 UTC, MTthoas commented on App.tsx
>  export type RootStackParamList = {
Fix moi ca

2024-02-06 20:02 UTC, merged